zeebe:
  client:
    broker.gatewayAddress: 127.0.0.1:26500
    security.plaintext: true

    worker:
      hazelcast:
        connection: localhost:5701
        clusterName: dev
        connectionTimeout: PT1M
      redis:
        connection: redis://localhost:6379

# Options: hazelcast | kafka | redis
# This config switches importers between the provided
# To use each of them, zeebe must be configured using hazelcast-exporter, kafka-exporter or redis-exporter, respectively
# See the examples in docker/docker-compose.yml in services.zeebe-hazelcast, services.zeebe-kafka, services-zeebe-redis
zeebe-importer: kafka

spring:
  output.ansi.enabled: ALWAYS
  profiles:
    active: kafka
  datasource:
    url: jdbc:postgresql://localhost:5432/monitor
    username: zeebe
    password: zeebe
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

  mustache:
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      expose-request-attributes: true

  data:
    web:
      pageable:
        default-page-size: 10

  kafka:
    template:
      default-topic: zeebe
    bootstrap-servers: b-1.zeebe.gprf4j.c3.kafka.ap-south-1.amazonaws.com:9092,b-3.zeebe.gprf4j.c3.kafka.ap-south-1.amazonaws.com:9092,b-2.zeebe.gprf4j.c3.kafka.ap-south-1.amazonaws.com:9092
    properties:
      request.timeout.ms: 20000
      retry.backoff.ms: 500
    group-id: zeebe-simple-monitor
    consumer:
      auto-offset-reset: earliest
      properties:
        # 1Mb (1*1024*1024), max size of batch
        max.partition.fetch.bytes: 1048576
        # Number of messages in batch received by kafka listener.
        # Works only if their size is less than 'max.partition.fetch.bytes'
        max.poll.records: 1000
    custom:
      # Set equal to number of topic partitions to handle them in parallel
      concurrency: 3
      retry:
        interval-ms: 30000
        max-attempts: 3

server:
  port: 8082
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force-response: true
  allowedOriginsUrls: ""

logging:
  level:
    root: INFO
    io.zeebe: INFO
    io.zeebe.monitor: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: zeebe-simple-monitor

white-label:
  logo.path: img/logo.png
  custom:
    title: Zeebe Simple Monitor
    css.path: css/custom.css
    js.path: js/custom.js
